### ISSUE TITLE
Add more fields to sync with mailchimp in form entries

### ISSUE THREAD

**Issue by lpirola** [ourcities/hub-api#31]
When anyone subscribe to our form entries system, a sync to mailchimp is done, but now we only sync basic fields, we want to add city and celular too.

**Comment by lpirola** [comment]
https://github.com/ourcities/hub-api/blob/master/app/models/form_entry.rb#L50

**Comment by lpirola** [comment]
Two fixes must be made: not sync when value is empty or 'Outra'; and only the field is named exactly cidade;

**Comment by igr-santos** [comment]
I think need to do export of informations by Widget, doesn't by Mobilization, because one mobilization has many FormWidget and each FormWidget has many lines of information.

It's possible to filter form_entries by widget_id?

**Comment by lpirola** [comment]
@igr-santos maybe this comment should be done on #33?

**Comment by igr-santos** [comment]
Thanks @lpirola fix comment
