### ISSUE TITLE
Save activists data and sync with mailchimp when use DirectPressure widget.

### ISSUE THREAD

**Issue by gabrielrtakeda** [ourcities/hub-api#39]
Client issue reference: ourcities/hub-client#127

Should create an endpoint do save activists data (firstname, lastname and email) that uses DirectPressure widget. And sync data with mailchimp API.

#### Endpoint
```
POST: /widget/:widget_id/fill
```

#### Example Payload (updated: 17/08/2016)
```json
{
  "fill": {
    "activist": {
      "firstname": "(string)",
      "lastname": "(string)",
      "email": "(string)"
    },
    "mail": {
      "cc": "(array)",
      "subject": "(string)",
      "body": "(string)"
    }
  }
}
```

#### Example Response Body:
```json
{
  "id": "(int)",
  "activist_id": "(int)",
  "widget_id": "(int)",
  "created_at": "(string:timestamp)",
  "updated_at": "(string:timestamp)",
  "count": "(int)"
}
```

**Comment by gabrielrtakeda** [comment]
Needs to add thank email send behaviour.

**Comment by gabrielrtakeda** [comment]
Commit reference: https://github.com/ourcities/hub-api/commit/9cf28d97f0b1574db35fa5d0da48c9113f8e046d

**Comment by igr-santos** [comment]
@gabrielrtakeda Why we don't try make pattern to request send mail? Like this:

```
{
    "widget_id": 3177,
    "activist": {
      "firstname": "Foo",
      "lastname": "Bar",
      "email": "foo201608151927@bar.org"
    },
    "mail": {
      "cc": [
        "target01@foo.gov.br",
        "target02@foo.gov.br",
        "target03@foo.gov.br"
      ],
      "subject": "Foo bar subject",
      "body": "Caro secretário, você está sendo pressionado!"
    }
}
```

**Comment by igr-santos** [comment]
Tasks:

- [ ] Send mail to activist when widget settings config autofire
- [ ] Send mail to cc config payload when `mail` set
- [ ] Save activist in database

**Comment by gabrielrtakeda** [comment]
Needs to change endpoint from `/activist_pressures` to `/widgets/:widget_id/fill`.

**Comment by gabrielrtakeda** [comment]
Because of the route change, the payload don't need to have `widget_id`. It is accessible via params.

**Comment by gabrielrtakeda** [comment]
Needs to send email to targets passed by payload.

**Comment by gabrielrtakeda** [comment]
Install [foreman](https://github.com/ddollar/foreman) gem to facilitates running application and workers concurrently on development environment.

**Comment by gabrielrtakeda** [comment]
Suggestion to send multiple emails with ActionMailer:
https://subvisual.co/blog/posts/66-sending-multiple-emails-with-actionmailer

**Comment by gabrielrtakeda** [comment]
Needs to add pressure count on response body.

**Comment by gabrielrtakeda** [comment]
Commit reference: https://github.com/ourcities/hub-api/commit/df01816b370eb2b1fa5ca98867e901a208b7b172

**Comment by gabrielrtakeda** [comment]
Current status of activist pressure create endpoint:

```
POST: /widget/:widget_id/fill
```

#### Example Payload:
```json
{
  "fill": {
    "activist": {
      "firstname": "(string)",
      "lastname": "(string)",
      "email": "(string)"
    },
    "mail": {
      "cc": "(array)",
      "subject": "(string)",
      "body": "(string)"
    }
  }
}
```

#### Example Response Body:
```json
{
  "id": "(int)",
  "activist_id": "(int)",
  "widget_id": "(int)",
  "created_at": "(string:timestamp)",
  "updated_at": "(string:timestamp)",
  "count": "(int)"
}
```

**Comment by gabrielrtakeda** [comment]
Needs to change email delivery strategy from `now` (sync) to `later` (async) due to a response performance issue.

**Comment by gabrielrtakeda** [comment]
It needs to load pressure count on widget fetch.

**Comment by gabrielrtakeda** [comment]
ourcities/hub-client#127 commit: https://github.com/ourcities/hub-api/commit/b19d4b37504fdfc422b9c1bd11d5846204d9a4bf

**Comment by gabrielrtakeda** [comment]
It needs to merge with master.

**Comment by gabrielrtakeda** [comment]
Merge commit reference: https://github.com/ourcities/hub-api/pull/40/commits/af64e9e979cb0034c1699d16649e76ea07329563
